/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popUp;
import database.koneksi;
import gui.DataWarga;
import gui.RangkingSpk;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;


/**
 *
 * @author zaeha
 */
public class popUpWarga extends javax.swing.JFrame {
    private Connection conn = new koneksi().kon();
    private DefaultTableModel tabmode;
    public RangkingSpk rangSPK = null;

    /**
     * Creates new form popUpWarga
     */
    public popUpWarga() {
        initComponents();
        dataTable();
        setLocationRelativeTo(this);
        
    }
    
    protected void dataTable (){
    Object [] Baris = {"NIK", "Nama", "Agama", "NoHP", " Jenkel", "tgl", "RT","Alamat"};
    tabmode = new DefaultTableModel(null, Baris);
    try {
        String isiTeks = tfCari.getText();
        
        String sql = "SELECT * from warga where no_ktp like '%"+isiTeks+"%' or nama like '%"+isiTeks+"%' order by no_ktp asc";
        Statement stat = conn.createStatement();
        ResultSet result = stat.executeQuery(sql);
        while (result.next()) {
        tabmode.addRow(new Object[]{
            result.getString(1),
            result.getString(2),
            result.getString(3),
            result.getString(4),
            result.getString(5),
            result.getString(6),
            result.getString(7),
            result.getString(8)
        });
        }
        tblPopWarga.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Data Gagal Diambil"+e);
        System.out.println(""+e);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPopWarga = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLabel1.setText("DATA WARGA");

        jButton1.setText("Cari");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        tblPopWarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPopWarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPopWargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPopWarga);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPopWargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPopWargaMouseClicked
        // TODO add your handling code here:
        int row = tblPopWarga.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel)tblPopWarga.getModel();
        String no_ktp = model.getValueAt(row, 0).toString();
        String nama = model.getValueAt(row, 1).toString();
        String agama =model.getValueAt(row, 2).toString();
//            switch (aGama) {
//                case "Item 1" :
//                        DataWarga.agama.setSelectedIndex(0);
//                        break;
//                case "Item 2" :
//                        cbAgama.setSelectedIndex(1);
//                        break;
//                case "Item 3" :
//                        cbAgama.setSelectedIndex(2);
//                        break;
//                case "Item 4" :
//                        cbAgama.setSelectedIndex(3);
//                        break;
//            }
        String noHP = model.getValueAt(row, 3).toString();
        String jenKel = model.getValueAt(row, 4).toString();
//            if (jenKel.equals("L")) {
//             rbtnL.setSelected(true);
//        } else {
//            rbtnP.setSelected(true);
//        };
//        try {
//            java.util.Date dateKlik = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row, 5));
//            jDateChooser1.setDate(dateKlik);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "ga bisa masuk tanggal nya"+e);
//        }
//        String rT =model.getValueAt(row, 6).toString();
//            switch (rT) {
//                case "Item 1" :
//                        cbRT.setSelectedIndex(0);
//                        break;
//                case "Item 2" :
//                        cbRT.setSelectedIndex(1);
//                        break;
//                case "Item 3" :
//                        cbRT.setSelectedIndex(2);
//                        break;
//                case "Item 4" :
//                        cbRT.setSelectedIndex(3);
//                        break;
//            }
//        tfaAlamat.setText(model.getValueAt(row, 7).toString());
//        tfNik.setText(model.getValueAt(row, 0).toString());
//    }                                     
    rangSPK.getDataWarga(no_ktp, nama);
    this.dispose();
    }//GEN-LAST:event_tblPopWargaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUpWarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPopWarga;
    private javax.swing.JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}
