/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popUp;

import database.koneksi;
import gui.DataAlternatifPage;
import gui.RangkingSpkPage;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Vector;

/**
 *
 * @author zaeha
 */
public class popUpAlternatif extends javax.swing.JFrame {

    private Connection conn = new koneksi().kon();
    public RangkingSpkPage alternatif = null;
    private DefaultTableModel tabmodeAlt;
    String[] bobot;

    /**
     * Creates new form popUpWarga
     */
    public popUpAlternatif() {
        initComponents();
        dataTable();
        setLocationRelativeTo(this);

    }

    private void dataTable() {
        // Pastikan tabmodeAlt diinisialisasi dengan benar
        if (tabmodeAlt == null) {
            tabmodeAlt = new DefaultTableModel();
            tabmodeAlt.addColumn("ID");
            tabmodeAlt.addColumn("NIK");
            tabmodeAlt.addColumn("NAMA WARGA");
            tabmodeAlt.addColumn("ID STAFF");
            tabmodeAlt.addColumn("NAMA STAFF");
            tabmodeAlt.addColumn("GOLONGAN");
            tblAlt.setModel(tabmodeAlt); // Atur model tabel ke tblAlt
        } else {
            // Bersihkan baris yang ada
            tabmodeAlt.setRowCount(0);
        }

        // Query untuk mendapatkan data kriteria
        String queryKriteria = "SELECT nama_kriteria FROM kriteria";
        // Query untuk mendapatkan data alternatif dan bobot
        String queryData = "SELECT a.id, a.no_ktp, a.nama_warga, a.id_staff, a.nama_staff, a.golongan, "
                + "GROUP_CONCAT(asub.nilai_bobot ORDER BY asub.id_kriteria) AS nilai_bobot "
                + "FROM alternatif a "
                + "JOIN alternatif_sub asub ON a.id = asub.id_alternatif "
                + "WHERE a.golongan = 'tidak mampu' "
                + "GROUP BY a.id, a.no_ktp, a.nama_warga, a.id_staff, a.nama_staff, a.golongan "
                + "ORDER BY a.id";

        try (PreparedStatement stmtKriteria = conn.prepareStatement(queryKriteria);
                ResultSet rsKriteria = stmtKriteria.executeQuery();
                PreparedStatement stmtData = conn.prepareStatement(queryData);
                ResultSet rsData = stmtData.executeQuery()) {

            // Buat model tabel untuk tabmodeBobot
            DefaultTableModel modelBobot = new DefaultTableModel();
            tblBobot.setModel(modelBobot); // Atur model tabel ke tblBobot

            // Tambahkan kolom ke model tabel berdasarkan data kriteria dari database
            while (rsKriteria.next()) {
                String namaKriteria = rsKriteria.getString("nama_kriteria");
                modelBobot.addColumn(namaKriteria);
            }

            // Dapatkan jumlah kolom dalam model tabel
            int numColumns = modelBobot.getColumnCount();

            // Isi data ke dalam model tabel tabmodeAlt dan tabmodeBobot
            while (rsData.next()) {
                int id = rsData.getInt("id");
                String noKtp = rsData.getString("no_ktp");
                String namaWarga = rsData.getString("nama_warga");
                String idStaff = rsData.getString("id_staff");
                String namaStaff = rsData.getString("nama_staff");
                String golongan = rsData.getString("golongan");
                String[] nilaiBobotArray = rsData.getString("nilai_bobot").split(",");

                // Tambahkan baris ke tabmodeAlt
                tabmodeAlt.addRow(new Object[]{id, noKtp, namaWarga, idStaff, namaStaff, golongan});

                // Buat baris untuk tabmodeBobot dengan nilai_bobot
                Object[] rowDataBobot = new Object[numColumns];
                for (int i = 0; i < nilaiBobotArray.length; i++) {
                    rowDataBobot[i] = Integer.parseInt(nilaiBobotArray[i]);
                }

                modelBobot.addRow(rowDataBobot);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlt = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBobot = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLabel1.setText("DATA ALTERNATIF");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        tblAlt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAltMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));

        tblBobot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBobot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBobotMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBobot);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(777, Short.MAX_VALUE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addContainerGap(657, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dataTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblAltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAltMouseClicked
        int row = tblAlt.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang valid dari tabel Alternatif.");
            return;
        }

        // Mendapatkan model dari tabel Alternatif
        DefaultTableModel modelAlt = (DefaultTableModel) tblAlt.getModel();

        // Mendapatkan nilai no_ktp dan nama dari tabel Alternatif
        String no_ktp = modelAlt.getValueAt(row, 1).toString();
        String nama = modelAlt.getValueAt(row, 2).toString();

        // Mendapatkan model dari tabel Bobot
        DefaultTableModel modelBobot = (DefaultTableModel) tblBobot.getModel();

        // Mengambil nilai bobot dari tabel Bobot untuk baris yang sesuai dengan pilihan pada tabel Alternatif
        StringBuilder bobotValues = new StringBuilder();
        for (int i = 0; i < modelBobot.getColumnCount(); i++) {
            Object value = modelBobot.getValueAt(row, i); // Menggunakan baris yang benar dari tabel Bobot
            if (value != null) {
                bobotValues.append(value.toString()).append(", ");
            }
        }

        // Menghapus koma terakhir
        if (bobotValues.length() > 0) {
            bobotValues.setLength(bobotValues.length() - 2);
        }

        // Mengubah StringBuilder ke String
        String bobotValuesStr = bobotValues.toString();

        // Menampilkan nilai bobot (atau melakukan sesuatu dengan nilai ini)
        JOptionPane.showMessageDialog(this, "Nilai bobot: " + bobotValuesStr);

        // Panggil metode untuk mendapatkan alternatif berdasarkan no_ktp, nama, dan bobotValuesStr
        alternatif.getAlternatif(no_ktp, nama, bobotValuesStr);
        

    }//GEN-LAST:event_tblAltMouseClicked

    private void tblBobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBobotMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBobotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUpAlternatif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAlt;
    private javax.swing.JTable tblBobot;
    private javax.swing.JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}
