/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import data.LoginData;
import database.koneksi;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author zaeha
 */

public class dashboard extends javax.swing.JFrame {
    LoginData Id = new LoginData();
    Connection conn;

    /**
     * Creates new form Dashboard
     */
    public dashboard() {
        initComponents();
        setLocationRelativeTo(this);
        conn = koneksi.kon();
        userName.setText(Id.getNama_login().toString()+"!");
        System.out.println(Id.getId_login());
        System.out.println(Id.getIzin_login());
        System.out.println(Id.getIzin_login());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        btnPenduduk = new javax.swing.JButton();
        btnKriterian = new javax.swing.JButton();
        btnAlternatif = new javax.swing.JButton();
        btnSPK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Selamat Datang ");

        userName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        userName.setText("namaUser");

        btnPenduduk.setText("Data Penduduk");
        btnPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendudukActionPerformed(evt);
            }
        });

        btnKriterian.setText("Data Kriteria");
        btnKriterian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKriterianActionPerformed(evt);
            }
        });

        btnAlternatif.setText("Data Alternatif");
        btnAlternatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternatifActionPerformed(evt);
            }
        });

        btnSPK.setText("Perhitungan SPK");
        btnSPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(userName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnPenduduk)
                        .addGap(107, 107, 107)
                        .addComponent(btnKriterian)
                        .addGap(69, 69, 69)
                        .addComponent(btnAlternatif)
                        .addGap(46, 46, 46)
                        .addComponent(btnSPK)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKriterian)
                    .addComponent(btnAlternatif)
                    .addComponent(btnSPK)
                    .addComponent(btnPenduduk))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendudukActionPerformed
        // TODO add your handling code here:
        new DataWarga().setVisible(true);
        
    }//GEN-LAST:event_btnPendudukActionPerformed

    private void btnKriterianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKriterianActionPerformed
        // TODO add your handling code here:
        new test().setVisible(true);
    }//GEN-LAST:event_btnKriterianActionPerformed

    private void btnAlternatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternatifActionPerformed
        // TODO add your handling code here:
        new DataAlternatif().setVisible(true);
    }//GEN-LAST:event_btnAlternatifActionPerformed

    private void btnSPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPKActionPerformed
        // TODO add your handling code here:
        new RangkingSpk().setVisible(true);
    }//GEN-LAST:event_btnSPKActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlternatif;
    private javax.swing.JButton btnKriterian;
    private javax.swing.JButton btnPenduduk;
    private javax.swing.JButton btnSPK;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
